#!/bin/bash

set -oue pipefail

if ! /usr/bin/flatpak remotes --columns=name | grep -qx fedora; then
  echo "No fedora flatpak to be found!"
  exit 0
fi

echo "Adding Flathub..."
for i in {1..10}; do
  if /usr/bin/flatpak remote-add \
    --if-not-exists \
    --system \
    flathub \
    https://dl.flathub.org/repo/flathub.flatpakrepo
  then
    break
  fi

  if [ "$i" -eq 10 ]; then
    echo "Unable to fetch the Flathub repository."
    exit 1
  fi

  echo "Flathub unavailable; retrying in 5 seconds..."
  sleep 5
done

echo "Replacing Fedora Flatpaks with Flathub"
TO_REPLACE=$(flatpak list --app --columns=application,origin | awk '$2 == "fedora" {print $1}')

/usr/bin/flatpak uninstall -y --noninteractive "${TO_REPLACE[@]}" &>/dev/null </dev/null
/usr/bin/flatpak install -y --noninteractive flathub "${TO_REPLACE[@]}" &>/dev/null </dev/null

echo "Removing flatpaks that were only from fedora flatpak"
/usr/bin/flatpak list --system --columns=ref,origin |
  /usr/bin/awk '$2 == "fedora" {print $1}' |
  xargs -r /usr/bin/flatpak uninstall -y --noninteractive

echo "Finally, remove fedora flatpak"
/usr/bin/flatpak remote-delete --system fedora
/usr/bin/flatpak remote-delete --system fedora-testing || true
